language: c
install: 
    - sudo apt-get install libelf-dev libglib2.0-dev python3-sphinx libblkid-dev python3-nose gettext python3-setuptools
    - sudo easy_install pip
    - sudo /usr/local/bin/pip install sphinx_bootstrap_theme
compiler:
  - clang
  - gcc
notifications:
  email:
    - sahib@online.de
    - thomas_d_j@yahoo.com.au

script: scons && sudo nosetests3
